spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env:
  test
girl:
  name: liming
  age: 20
